version: '3.8'

services:
  call_analysis:
    image: django_call_analysis
    build: .
    container_name: call_analysis
    ports:
      - "11434:11434"  # Ollama 기본 포트
      - "17777:17777"
    volumes:
      - /data:/data  # 호스트의 /data를 컨테이너의 /data로 직접 마운트
    restart: unless-stopped
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]